# Generated by Django 2.2 on 2022-05-03 05:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250)),
                ('bed_room', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('bed_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('both', 'Both')], default='adult', max_length=10)),
                ('guest', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('property_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('contact_number', models.BigIntegerField(max_length=14)),
                ('cancellation', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10)),
                ('Description', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='RealEstate_App.Address')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='RealEstate_App.Room')),
            ],
        ),
    ]
