# Generated by Django 4.0.4 on 2022-05-03 05:14

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('RealEstate_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
