# Generated by Django 4.0.4 on 2022-05-03 05:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0002_address_slug_property_features_room_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bed',
            new_name='beds',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
