# Generated by Django 4.0.4 on 2022-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0004_rename_room_name_room_room_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
