# Generated by Django 4.0.4 on 2022-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate_App', '0005_alter_property_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
